module.exports = {
  ROLES: Object.freeze({
    USER: process.env.USER_ROLE,
    EMPLOYEE: process.env.EMPLOYEE_ROLE,
    ADMIN: process.env.ADMIN_ROLE,
  }),
  PERMISSIONS: Object.freeze({
    USER: process.env.USER_ROLE,
    ADMIN: process.env.ADMIN_ROLE,
    EMPLOYEE: process.env.EMPLOYEE_PERMISSIONS,
    OPTOMETRIST: ["Customers"],
    TECHNICAL_MANAGER: ["Product"],
    ALL: `${process.env.ADMIN_ROLE}`,
  }),
  accessTokenCookieOptions: Object.freeze({
    maxAge: 1000 * 60 * 60 * 24,
    httpOnly: true,
    signed: true,
    sameSite: "Lax",
    secure: process.env.NODE_ENV !== "development",
    domain: process.env.DOMAIN,
  }),
  refreshTokenCookieOptions: Object.freeze({
    maxAge: 1000 * 60 * 60 * 24 * 365,
    httpOnly: true,
    signed: true,
    sameSite: "Lax",
    secure: process.env.NODE_ENV !== "development",
    domain: process.env.DOMAIN,
  }),
  BlackListFields: Object.freeze([
    "otp",
    "id",
    "roleId",
    "permissionId",
    "userId",
    "rolePermissionId",
    "role",
    "expiresIn",
    "code",
    "createdAt",
    "updatedAt",
    "employee",
  ]),
};
